[project]
name = "07-dynamodb-vector-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.100",
    "common",
    "datasets",
]

[tool.uv.sources]
common = { path = "../../common", editable = true }
datasets = { path = "../../datasets", editable = true }
