[project]
name = "04-evaluation"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.39",
    "common",
    "datasets",
]

[tool.uv.sources]
datasets = { path = "../../datasets", editable = true }
common = { path = "../../common", editable = true }
